server:
  port: 8080
  shutdown: graceful

spring:
  datasource:
    url: ${DB_DATASOURCE_URL}
    username: ${DB_USER_NAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

    properties:
      hibernate:
        format_sql: true
        show-sql: true

    database-platform: org.hibernate.dialect.MariaDBDialect

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  jackson:
    time-zone: Asia/Seoul

  social:
    google:
      url:
        profile: https://www.googleapis.com/oauth2/v3/userinfo
    kakao:
      url:
        profile: https://kapi.kakao.com/v2/user/me
    apple:
      grant-type: authorization_code
      client-id: ${APPLE_CLIENT_ID}
      key-id: ${APPLE_KEY_ID}
      team-id: ${APPLE_TEAM_ID}
      audience: https://appleid.apple.com
      private-key: ${APPLE_PRIVATE_KEY}

jwt:
  secret: ${JWT_SECRET}

  access:
    expiration: 3600000 # 1??
    header: X-AUTH-TOKEN

  refresh:
    expiration: 1209600000 #2?
    header: rememberedToken

bootpay:
  key:
    rest-api: ${BOOTPAY_REST_KEY}
    private: ${BOOTPAY_PRIVATE_KEY}

cloud:
  aws:
    credentials:
      access-key: ${S3_ACCESS_KEY}
      secret-key: ${S3_SECRET_KEY}
    s3:
      bucket-name:
        brand: ${S3_BRAND_BUCKET}
        perfume: ${S3_PERFUME_BUCKET}
        member: ${S3_MEMBER_BUCKET}
        community: ${S3_COMMUNITY_BUCKET}
        magazine: ${S3_MAGAZINE_BUCKET}
        note: ${S3_NOTE_BUCKET}
    region:
      static: ap-northeast-2
    stack:
      auto: false

firebase:
  config: ${FIREBASE_CONFIG}

default:
  profile: ${S3_PROFILE}
  main: ${S3_MAIN}
  maintest: ${S3_MAIN_TEST}

survey:
  image:
    background: ${S3_SURVEY_BACKGROUND}
    first: ${S3_SURVEY_FIRST}
    second: ${S3_SURVEY_SECOND}