spring:
  profiles:
    group:
      local:
        - local
        - jwt
        - oauth2
        - s3
        - payment
      prod:
        - aws
        - jwt
        - oauth2
        - s3
        - payment
    active: ${active.profiles}
