name: Update Hotfix Branch From Develop!

on:
  push:
    branches:
      - develop

jobs:
  update-hotfix:
    runs-on: ubuntu-latest

    steps:
      - name: check out repository
        uses: actions/checkout@v3
        with:
          ref: develop

      - name: Set up Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: checkout hotfix
        run: |
          git fetch origin hotfix
          git checkout hotfix

      - name: Rebase
        run: |
          git rebase origin/develop

      - name: Push changes
        run: |
          git push origin hotfix --force-with-lease
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}